### ISSUE TITLE
@auth directive with 'oidc' provider error

### ISSUE THREAD

**Issue by zgajo** [kcwinner/cdk-appsync-transformer#135]
**Current Behavior**
I'm trying to set up the OIDC authentication and retrieving the error: 
_@auth directive with 'oidc' provider found, but the project has no OPENID_CONNECT authentication provider configured._

I'm using the Cognito from another account as the OIDC.

The error happens running the _cdk synth_ command.

Code that doesn't work: 
```
schema.graphql

// this is copied from https://aws.amazon.com/blogs/mobile/graphql-security-appsync-amplify/

type Post
  @model
  @auth(
    rules: [
      { allow: owner, provider: oidc, identityClaim: "custom:id" }
      {
        allow: groups
        groups: ["Bloggers", "Readers"]
        operations: [read]
        provider: oidc
        groupClaim: "custom:groups"
      }
    ]
  ) {
  id: ID!
  description: String
}
```

```
lib/cdk-init.ts

   const myAppSync = new AppSyncTransformer(this, "my-cool-api", {
      schemaPath: "./schema.graphql",
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.OIDC,
          openIdConnectConfig: {
            oidcProvider: "https://cognito-idp.us-east-1.amazonaws.com/us-east-XXX",
          },
        },
      },
      xrayEnabled: true,
    });

```

If I remove  _provider: oidc_  and fields related to it, then everything works fine.

**What should happen**
It should generate the VTL files and GraphQL schema without the error. 

Using  "cdk-appsync-transformer": "^1.77.8"

The same example is tested using only AWS Ampify, and everything works without error.

**Comment by zgajo** [comment]
I've found the bug:

**SOLUTION:**
inside cdk-appsync-transformer/schema-transformer.js
this.authTransformerConfig.additionalAuthenticationProviders 
add: 
```
{
     authenticationType: "OPENID_CONNECT",
     openIDConnectConfig: {
            oidcProvider: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XXX",
     },
}
```

**Comment by kcwinner** [comment]
@zgajo Will add this in tomorrow!

**Comment by kcwinner** [comment]
@zgajo version `1.77.9` contains your fix!
