### ISSUE TITLE
Add DynamoDB stream option

### ISSUE THREAD

**Issue by zgajo** [kcwinner/cdk-appsync-transformer#158]
I think that there is a great feature to have the possibility to add streams to the specific table.
I've tested with the following code, and it works.

```
appsync-transformer.d.ts

import { StreamViewType } from '@aws-cdk/aws-dynamodb';


export interface AppSyncTransformerProps {


/**
     * Add streams to specific table
     * 
     * *stream*: DynamoDB stream type
     * 
     * *table*: name of the type for which you want to enable the stream
     *
     * @default undefined
     * @experimental
     */
    readonly streamPerTable?: Array<{stream: StreamViewType, table: string}>; 

}
```

```
appsync-transformer.ts

constructor (){
  this.streamPerTable = props.streamPerTable || []
}

createTable(){
  const streamFound = this.streamPerTable.find(obj => `${obj.table}Table` === tableData.tableName)

  let tableProps = {
            billingMode: aws_dynamodb_1.BillingMode.PAY_PER_REQUEST,
            partitionKey: {
                name: tableData.partitionKey.name,
                type: this.convertAttributeType(tableData.partitionKey.type),
            },
            ...(streamFound ? {stream: streamFound.stream}  : null)
        };
}
```

During the appsync creation:
```
const myAppSync = new AppSyncTransformer(this, `test-db`, {
      schemaPath: "./schema.graphql",
      postCdkTransformers: [new AssertTransformer()],
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.OIDC,
          openIdConnectConfig: {
            oidcProvider: process.env.OIDC_PROVIDER as string,
          },
        },
        additionalAuthorizationModes: [
          {
            authorizationType: appsync.AuthorizationType.IAM,
          },
        ],
      },
      xrayEnabled: true,
      fieldLogLevel: FieldLogLevel.ALL,
      streamPerTable: [{ stream: dynamodb.StreamViewType.NEW_IMAGE, table: "Sample" }],
    });
```

What do you think @kcwinner, can you add this or there is a better solution for this?

**Comment by zgajo** [comment]
There are additional things to be made, just because of the CDK [limitation](https://github.com/aws/aws-cdk/issues/8903).

If we want to add a lambda trigger for a specific table stream, we need to fetch the table and set it as a first argument for the DynamoEventSource.
But if we retrieve the table using the from* functions, example using the **dynamodb.Table.fromTableAttributes** or **dynamodb.Table.fromTableName** , the tableStreamArn is going to be undefined.

To solve this I've added tableMap property to be returned on AppSync stack creation. 
This property will have a reference directly to the table, and with this approach, we'll have a direct reference to the table, and DynamoEventSource can use the  tableStreamArn from a table.


```
 appsync-transformer.d.ts

import { StreamViewType, Table } from '@aws-cdk/aws-dynamodb';


export declare class AppSyncTransformer extends Construct {
 /**
     * (experimental) Map of cdk table tokens to table.
     *
     * @experimental
     */
    readonly tableMap: {
        [name: string]: Table;
    };
}
```

```
appsync-transformer.ts

constructor (){
   ...
   this.tableMap = {}
   this.tableNameMap = this.createTablesAndResolvers(tableData, resolvers);
}

createTablesAndResolvers(tableData, resolvers) {
           const dynamoDbConfig = dataSource.ds.dynamoDbConfig;
            tableNameMap[tableKey] = dynamoDbConfig.tableName;
            this.tableMap[tableKey] = table;
}
```


And we can use it on the lambda trigger creation
```
 lambdaDn.addEventSource(
      new DynamoEventSource(myAppSync.tableMap["SampleTable"], {
        startingPosition: StartingPosition.TRIM_HORIZON,
      })
    );
```

**Comment by kcwinner** [comment]
@zgajo thanks for this! Looks like an interesting take. I definitely like the switch of moving to the tableMap as well. I've got this started in a branch. I'm debating on deprecating `tableNameMap` since you can get it from the `tableMap`, but it does serve a nice usecase of passing tableNameMap to a Lambda function without additional work on the user end.

As for the streams, I was hoping for a way to add a stream via some sort of "convenience" method like I did for the Lambda functions. However, you can only add the stream to the L2 table from initial props. But I was thinking maybe adding a convenience method anyway and just adding it to the L1 construct. Something like:

```
// pseudo code
public addStreamToTable(tableName: string) {
  const orderTable = this.nestedAppsyncStack.node.findChild(tableName) as CfnTable;
  orderTable.streamSpecification = ...
}
```

**Comment by zgajo** [comment]
Hi @kcwinner, can you please tell me what's the status of this feature?

**Comment by kcwinner** [comment]
@zgajo Added in today. Two methods for adding: https://github.com/kcwinner/cdk-appsync-transformer#dynamodb-streams
