### ISSUE TITLE
Overwriting and customizing resolvers

### ISSUE THREAD

**Issue by mikkom** [kcwinner/cdk-appsync-transformer#213]
Is it possible to overwrite and/or customize resolvers similar to what Amplify CLI allows (https://docs.amplify.aws/cli/graphql-transformer/resolvers) using this project? I did notice the `@mapped` directive but is that for a slightly different use case? The documentation for that directive was a bit sparse so my understanding can well be a bit off here 🙂

**Comment by huss-jay** [comment]
any updates on this? would love to to be able to overwrite or customize the resolvers that amplify CLI generates

**Comment by kcwinner** [comment]
Things have been really busy for me lately so apologies in getting back to this so late. Have an idea in the works for this.

**Comment by kcwinner** [comment]
This PR will add support for creating custom none resolvers. Next will be adding in support for overwriting 
https://github.com/kcwinner/cdk-appsync-transformer/pull/284

**Comment by kcwinner** [comment]
Here is what I've done for overriding mapping templates. You can specify the request and/or response
https://github.com/kcwinner/cdk-appsync-transformer/pull/285
