### ISSUE TITLE
Feature request: ability to override table names 

### ISSUE THREAD

**Issue by neilferreira** [kcwinner/cdk-appsync-transformer#214]
At the moment my table names are extremely long and make the DynamoDB UI in the AWS console quite hard to use and distinguish the tables from one another (as the names are cropped).

An example,  I have a GraphQL model called "Directory" - this is my table name

> APIStack-BlahappsyncnestedstackNestedStackappsyncnestedstackNestedStackResourceB32A4078-QHOIR25MRDJL-DirectoryTable8D5AD835-1F6H4LDFTFI3O

I reached out to @kcwinner via Twitter for assistance, who recommended overriding the table name using the table map, this doesn't appear to be possible, however.

```
this.api.tableMap.DirectoryTable.tableName = "Directories";
eror TS2540: Cannot assign to 'tableName' because it is a read-only property.
```

Suggestion:
Introduce a "tableNameMap" argument when creating the API:

e.g.
```
this.api = new AppSyncTransformer(this, "Blah", {
      tableNameMap: {
        DirectoryTable: "Directories",
      },
      schemaPath: __dirname + "/schemas/schema.graphql",
```

**Comment by mikkom** [comment]
I have noticed the same annoyance myself. The repetition of "appsyncnestedstackNestedStack" seems particularly unnecessary. Just finding a way to trim that part would already be a clear improvement.

**Comment by kcwinner** [comment]
In the meantime you can do something like this
```ts
for (const [name, table] of Object.entries(this.appsyncTransformer.tableMap)) {
  const cfnTable = table.node.defaultChild as CfnTable;
  cfnTable.tableName = name;
}
```

The `name` is the name from the map (e.g. `CustomerTable`. And will result in something like this
```
    "CustomerTable260DCC08": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
        "KeySchema": [
          {
            "AttributeName": "id",
            "KeyType": "HASH"
          }
        ],
        "AttributeDefinitions": [
          {
            "AttributeName": "id",
            "AttributeType": "S"
          }
        ],
        "BillingMode": "PAY_PER_REQUEST",
        "TableName": "CustomerTable"
      },
      "UpdateReplacePolicy": "Retain",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "aws:cdk:path": "table-test-dev/appsync-api/appsync-nested-stack/CustomerTable/Resource"
      }
    }
```

**Comment by SchollSimon** [comment]
The provided solution is working for me! Thank you! I don't think the default naming convention should be discarded, it is ugly and it does not makes sense in this case. But as i noticed that is how AWS does it everywhere. E.g.: Creating a lambda function in your nested stack will also result in some long stack related name. 

So it makes more sense to do configure table names yourself. Especially when it comes to large business applications where you want to have unique table names.

**Comment by kcwinner** [comment]
Yes, when using CloudFormation naming you get unique values for your resources. This is my preference and many of my colleagues since changing a resource name often results in replacement. However, some of the names are less human readable.

I've merged in a prop so you can specify your table names and the nested stack name if you want. I can't remove the name by default as that would be a breaking change to others using it already.
