### ISSUE TITLE
Feature request: JS resolver instead of VTL

### ISSUE THREAD

**Issue by flochaz** [kcwinner/cdk-appsync-transformer#528]
Since now we can write resolver mapping template in JS (https://aws.amazon.com/blogs/aws/aws-appsync-graphql-apis-supports-javascript-resolvers/) it would be awesome to replace the VTL version by JS one .

**Comment by rodrigomata** [comment]
Is the project still maintained? I saw this issue being closed but it would be really helpful to have this implemented
